[build-system]
requires = [ "setuptools", "wheel", "Cython", "numpy", "scipy" ]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-all = "yum -y install lapack-devel blas-devel openblas-devel atlas-devel"
skip = "*-manylinux_i686"

[tool.cibuildwheel.macos]
skip = "pp*"
